/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzeria;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Wika
 */
public class Edycja_skladnikow extends javax.swing.JFrame {

    Connection con;
    Statement stmt1, stmt2, stmt3, stmt4, stmt5, stmt6;
    ResultSet res1, res2, res3, res4, res5, res6;
    DefaultTableModel model;
    static Zamowienia zam;
    float cenam = 0;
    float cenas = 0;
    float cenad = 0;

    /**
     * Creates new form Edycja_skladnikow
     */
    public Edycja_skladnikow(Zamowienia zam) {
        this.zam = zam;
        initComponents();
        model = (DefaultTableModel) tabelka.getModel();
        panel_edycji.setVisible(false);
        POLE_NOWA_DOST.setVisible(false);
        panel_tabelka_skl.setVisible(false);
    }

    Edycja_skladnikow() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        powrot = new javax.swing.JButton();
        panel_tabelka_skl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelka = new javax.swing.JTable();
        usuń = new javax.swing.JButton();
        edytuj = new javax.swing.JButton();
        dodaj = new javax.swing.JButton();
        panel_edycji = new javax.swing.JPanel();
        wyczysc = new javax.swing.JButton();
        anuluj = new javax.swing.JButton();
        zapisz = new javax.swing.JButton();
        nr = new javax.swing.JLabel();
        cena_mala = new javax.swing.JLabel();
        cena_srednia = new javax.swing.JLabel();
        cena_duza = new javax.swing.JLabel();
        rodzaj = new javax.swing.JLabel();
        nazwa = new javax.swing.JLabel();
        POLE_NUMER = new javax.swing.JTextField();
        POLE_NAZWA = new javax.swing.JTextField();
        POLE_NOWA_DOST = new javax.swing.JTextField();
        POLE_CENA_MALA = new javax.swing.JTextField();
        POLE_CENA_SREDNIA = new javax.swing.JTextField();
        POLE_CENA_DUZA = new javax.swing.JTextField();
        POLE_RODZAJ = new javax.swing.JComboBox();
        nowa_opcja_skl = new javax.swing.JToggleButton();
        pole_dost_skl = new javax.swing.JComboBox<>();
        rodzaj1 = new javax.swing.JLabel();
        nowa_opcja1 = new javax.swing.JToggleButton();
        POLE_NOWY_RODZAJ1 = new javax.swing.JTextField();
        komunikat = new javax.swing.JLabel();
        kom = new javax.swing.JLabel();
        przegladaj = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1239, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        powrot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        powrot.setText("Powrót");
        powrot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                powrotActionPerformed(evt);
            }
        });
        getContentPane().add(powrot, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 160, 60));

        panel_tabelka_skl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelka.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nr", "Nazwa", "Rodzaj", "Cena dla małej pizzy", "Cena dla średniej pizzy", "Cena dla dużej pizzy", "Dostępność"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelka);
        if (tabelka.getColumnModel().getColumnCount() > 0) {
            tabelka.getColumnModel().getColumn(0).setMinWidth(30);
            tabelka.getColumnModel().getColumn(0).setPreferredWidth(30);
            tabelka.getColumnModel().getColumn(0).setMaxWidth(30);
            tabelka.getColumnModel().getColumn(2).setResizable(false);
            tabelka.getColumnModel().getColumn(4).setResizable(false);
            tabelka.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        panel_tabelka_skl.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 980, 200));

        usuń.setText("Usuń");
        usuń.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuńActionPerformed(evt);
            }
        });
        panel_tabelka_skl.add(usuń, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 105, 36));

        edytuj.setText("Edytuj");
        edytuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edytujActionPerformed(evt);
            }
        });
        panel_tabelka_skl.add(edytuj, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 98, 36));

        dodaj.setText("Dodaj");
        dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodajActionPerformed(evt);
            }
        });
        panel_tabelka_skl.add(dodaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 103, 36));

        panel_edycji.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wyczysc.setText("Wyczyść");
        wyczysc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyczyscActionPerformed(evt);
            }
        });
        panel_edycji.add(wyczysc, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, 130, 40));

        anuluj.setText("Anuluj");
        anuluj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujActionPerformed(evt);
            }
        });
        panel_edycji.add(anuluj, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 90, 130, 40));

        zapisz.setText("Zapisz");
        zapisz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapiszActionPerformed(evt);
            }
        });
        panel_edycji.add(zapisz, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 140, 130, 40));

        nr.setText("Nr");
        panel_edycji.add(nr, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 30, 45, -1));

        cena_mala.setText("Cena dla małej pizzy,zł.*");
        panel_edycji.add(cena_mala, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        cena_srednia.setText("Cena dla średniej pizzy,zł.*");
        panel_edycji.add(cena_srednia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        cena_duza.setText("Cena dla dużej pizzy,zł.*");
        panel_edycji.add(cena_duza, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        rodzaj.setText("Dostępność*");
        panel_edycji.add(rodzaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, -1, -1));

        nazwa.setText("Nazwa*");
        panel_edycji.add(nazwa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        POLE_NUMER.setEnabled(false);
        POLE_NUMER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POLE_NUMERActionPerformed(evt);
            }
        });
        panel_edycji.add(POLE_NUMER, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 43, 30));
        panel_edycji.add(POLE_NAZWA, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 110, 30));

        POLE_NOWA_DOST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POLE_NOWA_DOSTActionPerformed(evt);
            }
        });
        panel_edycji.add(POLE_NOWA_DOST, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 110, 30));
        panel_edycji.add(POLE_CENA_MALA, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 102, 30));
        panel_edycji.add(POLE_CENA_SREDNIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 100, 30));
        panel_edycji.add(POLE_CENA_DUZA, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 100, 30));

        POLE_RODZAJ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "" }));
        POLE_RODZAJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POLE_RODZAJActionPerformed(evt);
            }
        });
        panel_edycji.add(POLE_RODZAJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        nowa_opcja_skl.setText("Nowa opcja");
        nowa_opcja_skl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowa_opcja_sklActionPerformed(evt);
            }
        });
        panel_edycji.add(nowa_opcja_skl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 110, -1));

        panel_edycji.add(pole_dost_skl, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 50, 110, 30));

        rodzaj1.setText("Rodzaj*");
        panel_edycji.add(rodzaj1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        nowa_opcja1.setText("Nowa opcja");
        nowa_opcja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nowa_opcja1ActionPerformed(evt);
            }
        });
        panel_edycji.add(nowa_opcja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, -1));

        POLE_NOWY_RODZAJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POLE_NOWY_RODZAJ1ActionPerformed(evt);
            }
        });
        panel_edycji.add(POLE_NOWY_RODZAJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 130, 30));

        komunikat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        panel_edycji.add(komunikat, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 540, 70));

        kom.setText("*-pola obowiązkowe do wypełnienia");
        panel_edycji.add(kom, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 320, 40));

        panel_tabelka_skl.add(panel_edycji, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1130, 260));

        getContentPane().add(panel_tabelka_skl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 1150, 560));

        przegladaj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        przegladaj.setText("Przeglądaj składniki");
        przegladaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przegladajActionPerformed(evt);
            }
        });
        getContentPane().add(przegladaj, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 260, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void powrotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_powrotActionPerformed
        zam.setVisible(true);
        dispose();
    }//GEN-LAST:event_powrotActionPerformed

    private void POLE_NOWA_DOSTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POLE_NOWA_DOSTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POLE_NOWA_DOSTActionPerformed

    private void przegladajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przegladajActionPerformed
        if (przegladaj.isSelected() == true) {
            panel_edycji.setVisible(false);
            panel_tabelka_skl.setVisible(true);
            czysctabelke();
            przegladaj(model);
        } else {
            panel_tabelka_skl.setVisible(false);
        }
    }//GEN-LAST:event_przegladajActionPerformed

    private void POLE_NUMERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POLE_NUMERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POLE_NUMERActionPerformed

    private void POLE_RODZAJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POLE_RODZAJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POLE_RODZAJActionPerformed

    private void nowa_opcja_sklActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowa_opcja_sklActionPerformed
        if (nowa_opcja_skl.isSelected() == true) {
            POLE_NOWA_DOST.setVisible(true);
            pole_dost_skl.setEnabled(false);
            pole_dost_skl.setSelectedIndex(0);
        } else {
            POLE_NOWA_DOST.setVisible(false);
            pole_dost_skl.setEnabled(true);
            POLE_NOWA_DOST.setText("");
        }
    }//GEN-LAST:event_nowa_opcja_sklActionPerformed

    private void usuńActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuńActionPerformed
        int j = tabelka.getRowCount();
        String ostt = tabelka.getValueAt(j - 1, 0).toString();
        int ost = Integer.parseInt(ostt);
        if (tabelka.getSelectedRowCount() > 0) {
            int wiersz = tabelka.getSelectedRow();
            String s = tabelka.getValueAt(wiersz, 0).toString();

            String usunwiersz = "delete from pizzeria.skladniki where id_skladnika=" + s;
            try {
                con = DriverManager.getConnection(
                        "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
                );
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Brak połączenia z bazą danych");
            }
            try {
                stmt5 = con.createStatement();
                stmt5.executeUpdate(usunwiersz);
                int id1 = Integer.parseInt(s);
                id1++;
                for (int i = id1; i <= ost; i++) {
                    String naprawid = "UPDATE skladniki SET id_skladnika =" + (i - 1) + " WHERE id_skladnika =" + i;
                    stmt5.executeUpdate(naprawid);
                }
            } catch (SQLException ex) {
               JOptionPane.showMessageDialog(null, "Brak połączenia z bazą danych");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nie wybrano wiersza!");
        }
        czysctabelke();
        przegladaj(model);


    }//GEN-LAST:event_usuńActionPerformed

    private void edytujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edytujActionPerformed
        if (tabelka.getSelectedRowCount() > 0) {
            wypiszrodzajdostepnosc();
            POLE_NAZWA.setText("");
            komunikat.setText("");
            POLE_NOWA_DOST.setText("");
            POLE_NOWY_RODZAJ1.setText("");
            POLE_RODZAJ.setSelectedIndex(0);
            pole_dost_skl.setSelectedIndex(0);
            POLE_CENA_DUZA.setText("");
            POLE_CENA_SREDNIA.setText("");
            POLE_CENA_MALA.setText("");
            panel_edycji.setVisible(true);
            nowa_opcja1.setSelected(false);
            nowa_opcja_skl.setSelected(false);
            POLE_NOWY_RODZAJ1.setVisible(false);
            POLE_NOWA_DOST.setVisible(false);
            POLE_RODZAJ.setEnabled(true);
            pole_dost_skl.setEnabled(true);
            int wybrwiersz = tabelka.getSelectedRow();
            int numer = Integer.parseInt(tabelka.getValueAt(wybrwiersz, 0).toString());
            POLE_NUMER.setText(numer + "");
        } else {
            JOptionPane.showMessageDialog(null, "Nie wybrano wiersza!");
        }

    }//GEN-LAST:event_edytujActionPerformed

    private void dodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodajActionPerformed
        POLE_NAZWA.setText("");
        POLE_NOWA_DOST.setText("");
        POLE_NOWY_RODZAJ1.setText("");
        komunikat.setText("");
        POLE_CENA_DUZA.setText("");
        POLE_CENA_SREDNIA.setText("");
        POLE_CENA_MALA.setText("");
        panel_edycji.setVisible(true);
        POLE_NOWY_RODZAJ1.setVisible(false);
        POLE_NOWA_DOST.setVisible(false);
        int numer = tabelka.getRowCount() + 1;
        POLE_NUMER.setText(numer + "");
        wypiszrodzajdostepnosc();
        POLE_RODZAJ.setSelectedIndex(0);
        pole_dost_skl.setSelectedIndex(0);
        nowa_opcja1.setSelected(false);
        nowa_opcja_skl.setSelected(false);
        POLE_RODZAJ.setEnabled(true);
        pole_dost_skl.setEnabled(true);
    }//GEN-LAST:event_dodajActionPerformed

    private void anulujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujActionPerformed
        panel_edycji.setVisible(false);
        czyscpola();
    }//GEN-LAST:event_anulujActionPerformed

    private void wyczyscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyczyscActionPerformed
        czyscpola();
    }//GEN-LAST:event_wyczyscActionPerformed

    private void zapiszActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapiszActionPerformed
        komunikat.setText("");
        int numer = tabelka.getRowCount() + 1;
        String nazwa = POLE_NAZWA.getText() + "";
        String dost = "";
        if (nowa_opcja_skl.isSelected()) {
            dost += POLE_NOWA_DOST.getText();
        } else {
            dost += pole_dost_skl.getSelectedItem().toString();
        }
        String rodzaj = "";
        if (nowa_opcja1.isSelected()) {
            rodzaj += POLE_NOWY_RODZAJ1.getText();
        } else {
            rodzaj += POLE_RODZAJ.getSelectedItem().toString();
        }
        if ((POLE_CENA_MALA.getText() != null && POLE_CENA_MALA.getText().length() > 0) && (POLE_CENA_DUZA.getText() != null && POLE_CENA_DUZA.getText().length() > 0) && (POLE_CENA_SREDNIA.getText() != null && POLE_CENA_SREDNIA.getText().length() > 0)) {
            try {
                cenam = Float.parseFloat(POLE_CENA_MALA.getText());
                cenas = Float.parseFloat(POLE_CENA_SREDNIA.getText());
                cenad = Float.parseFloat(POLE_CENA_DUZA.getText());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Niepoprawny format ceny!");
            }
        }
        if (nazwa.equals("") || rodzaj.equals("") || cenam == 0 || cenas == 0 || cenad == 0 || dost.equals("")) {
            komunikat.setText("Brak  danych!");
            komunikat.setForeground(Color.red);
        } else {
            try {
                con = DriverManager.getConnection(
                        "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
                );
                stmt4 = con.createStatement();
                String insert = "";
                if (tabelka.getSelectedRow() < 0) {
                    insert = "INSERT INTO skladniki VALUES(" + numer + "," + cenam + "," + cenas + "," + cenad + ",'" + rodzaj + "','" + nazwa + "','" + dost + "')";
                    stmt3.executeUpdate(insert);
                    numer++;
                    POLE_NUMER.setText(numer + "");
                } else {
                    int wiersz = tabelka.getSelectedRow();
                    String s = tabelka.getValueAt(wiersz, 0).toString();
                    insert = "UPDATE skladniki SET cena_skl_mala=" + cenam + ", cena_skl_srednia=" + cenas + ", cena_skl_duza=" + cenad
                            + ", rodzaj='" + rodzaj + "', nazwa='" + nazwa + "', dostepnosc='" + dost + "' WHERE id_skladnika=" + s;
                    stmt3.executeUpdate(insert);
                }
                czyscpola();
                komunikat.setText("Nowy składnik został dodany do bazy systemu");
                komunikat.setForeground(Color.DARK_GRAY);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Błąd zapisu!");
            }
            czysctabelke();
            przegladaj(model);
        }
    }//GEN-LAST:event_zapiszActionPerformed

    private void nowa_opcja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nowa_opcja1ActionPerformed
        if (nowa_opcja1.isSelected() == true) {
            POLE_NOWY_RODZAJ1.setVisible(true);
            POLE_RODZAJ.setEnabled(false);
            POLE_RODZAJ.setSelectedIndex(0);
        } else {
            POLE_NOWY_RODZAJ1.setVisible(false);
            POLE_RODZAJ.setEnabled(true);
            POLE_NOWY_RODZAJ1.setText("");
        }
    }//GEN-LAST:event_nowa_opcja1ActionPerformed

    private void POLE_NOWY_RODZAJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POLE_NOWY_RODZAJ1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POLE_NOWY_RODZAJ1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edycja_skladnikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edycja_skladnikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edycja_skladnikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edycja_skladnikow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edycja_skladnikow(zam).setVisible(true);
            }
        });
    }

    void wypiszrodzajdostepnosc() {
        POLE_RODZAJ.removeAllItems();
        pole_dost_skl.removeAllItems();
        try {
            con = DriverManager.getConnection(
                    "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
            );
            stmt3 = con.createStatement();
            res3 = stmt3.executeQuery(
                    "select distinct(rodzaj) from SKLADNIKI"
            );
            stmt6 = con.createStatement();
            res6 = stmt6.executeQuery(
                    "select distinct(dostepnosc) from SKLADNIKI"
            );
        } catch (Exception e) {

        }
        try {
            if (POLE_RODZAJ.getItemCount() == 0) {
                POLE_RODZAJ.addItem("");
                while (res3.next()) {
                    POLE_RODZAJ.addItem(res3.getString("rodzaj"));
                }
            }
            if (pole_dost_skl.getItemCount() == 0) {
                pole_dost_skl.addItem("");
                while (res6.next()) {
                    pole_dost_skl.addItem(res6.getString("dostepnosc"));
                }
            }

        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Brak połączenia z bazą danych");
        }

    }

    void przegladaj(DefaultTableModel model) {

        try {
            con = DriverManager.getConnection(
                    "jdbc:derby://localhost:1527/BazaPizzerii", "pizzeria", "pizzeria"
            );
            stmt1 = con.createStatement();
            res1 = stmt1.executeQuery(
                    "select * from SKLADNIKI order by id_skladnika"
            );
            stmt2 = con.createStatement();
            res2 = stmt2.executeQuery(
                    "select count(*) from SKLADNIKI "
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Brak połączenia z bazą danych");
        }
        try {

            while (res1.next()) {

                int nr = res1.getInt("id_skladnika");
                String cena_mala = res1.getString("cena_skl_mala") + " zł";
                String cena_srednia = res1.getString("cena_skl_srednia") + " zł";
                String cena_duza = res1.getString("cena_skl_duza") + " zł";
                String rodzaj = res1.getString("rodzaj");
                String nazwa = res1.getString("nazwa");
                String dost = res1.getString("dostepnosc");

                Object[] row = {nr, nazwa, rodzaj, cena_mala, cena_srednia, cena_duza, dost};
                model.addRow(row);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Brak połączenia z bazą danych");
        }
        tabelka.setModel(model);

    }

    void czysctabelke() {
        for (int i = model.getRowCount() - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }

    void czyscpola() {
        POLE_NAZWA.setText("");
        POLE_NOWA_DOST.setText("");
        POLE_NOWY_RODZAJ1.setText("");
        komunikat.setText("");
        POLE_CENA_DUZA.setText("");
        POLE_CENA_SREDNIA.setText("");
        POLE_CENA_MALA.setText("");
        POLE_RODZAJ.setSelectedIndex(0);
        pole_dost_skl.setSelectedIndex(0);
        nowa_opcja1.setSelected(false);
        nowa_opcja_skl.setSelected(false);
        POLE_RODZAJ.setEnabled(true);
        pole_dost_skl.setEnabled(true);
        POLE_NOWA_DOST.setVisible(false);
        POLE_NOWY_RODZAJ1.setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField POLE_CENA_DUZA;
    private javax.swing.JTextField POLE_CENA_MALA;
    private javax.swing.JTextField POLE_CENA_SREDNIA;
    private javax.swing.JTextField POLE_NAZWA;
    private javax.swing.JTextField POLE_NOWA_DOST;
    private javax.swing.JTextField POLE_NOWY_RODZAJ1;
    private javax.swing.JTextField POLE_NUMER;
    private javax.swing.JComboBox POLE_RODZAJ;
    private javax.swing.JButton anuluj;
    private javax.swing.JLabel cena_duza;
    private javax.swing.JLabel cena_mala;
    private javax.swing.JLabel cena_srednia;
    private javax.swing.JButton dodaj;
    private javax.swing.JButton edytuj;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kom;
    private javax.swing.JLabel komunikat;
    private javax.swing.JLabel nazwa;
    private javax.swing.JToggleButton nowa_opcja1;
    private javax.swing.JToggleButton nowa_opcja_skl;
    private javax.swing.JLabel nr;
    private javax.swing.JPanel panel_edycji;
    private javax.swing.JPanel panel_tabelka_skl;
    private javax.swing.JComboBox<String> pole_dost_skl;
    private javax.swing.JButton powrot;
    private javax.swing.JToggleButton przegladaj;
    private javax.swing.JLabel rodzaj;
    private javax.swing.JLabel rodzaj1;
    private javax.swing.JTable tabelka;
    private javax.swing.JButton usuń;
    private javax.swing.JButton wyczysc;
    private javax.swing.JButton zapisz;
    // End of variables declaration//GEN-END:variables
}
